package vn.poly.toanthptqg.activity;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.widget.ImageView;
import android.widget.TextView;

import vn.poly.toanthptqg.R;

public class ListQuestionDidActivity extends AppCompatActivity {

    private TextView tvQuestion1;
    private ImageView imgResult1;
    private TextView tvQuestion2;
    private ImageView imgResult2;
    private TextView tvQuestion3;
    private ImageView imgResult3;
    private TextView tvQuestion4;
    private ImageView imgResult4;
    private TextView tvQuestion5;
    private ImageView imgResult5;
    private TextView tvQuestion6;
    private ImageView imgResult6;
    private TextView tvQuestion7;
    private ImageView imgResult7;
    private TextView tvQuestion8;
    private ImageView imgResult8;
    private TextView tvQuestion9;
    private ImageView imgResult9;
    private TextView tvQuestion10;
    private ImageView imgResult10;
    private TextView tvQuestion11;
    private ImageView imgResult11;
    private TextView tvQuestion12;
    private ImageView imgResult12;
    private TextView tvQuestion13;
    private ImageView imgResult13;
    private TextView tvQuestion14;
    private ImageView imgResult14;
    private TextView tvQuestion15;
    private ImageView imgResult15;
    private TextView tvQuestion16;
    private ImageView imgResult16;
    private TextView tvQuestion17;
    private ImageView imgResult17;
    private TextView tvQuestion18;
    private ImageView imgResult18;
    private TextView tvQuestion19;
    private ImageView imgResult19;
    private TextView tvQuestion20;
    private ImageView imgResult20;
    private TextView tvQuestion21;
    private ImageView imgResult21;
    private TextView tvQuestion22;
    private ImageView imgResult22;
    private TextView tvQuestion23;
    private ImageView imgResult23;
    private TextView tvQuestion24;
    private ImageView imgResult24;
    private TextView tvQuestion25;
    private ImageView imgResult25;
    private TextView tvQuestion26;
    private ImageView imgResult26;
    private TextView tvQuestion27;
    private ImageView imgResult27;
    private TextView tvQuestion28;
    private ImageView imgResult28;
    private TextView tvQuestion29;
    private ImageView imgResult29;
    private TextView tvQuestion30;
    private ImageView imgResult30;
    private TextView tvQuestion31;
    private ImageView imgResult31;
    private TextView tvQuestion32;
    private ImageView imgResult32;
    private TextView tvQuestion33;
    private ImageView imgResult33;
    private TextView tvQuestion34;
    private ImageView imgResult34;
    private TextView tvQuestion35;
    private ImageView imgResult35;
    private TextView tvQuestion36;
    private ImageView imgResult36;
    private TextView tvQuestion37;
    private ImageView imgResult37;
    private TextView tvQuestion38;
    private ImageView imgResult38;
    private TextView tvQuestion39;
    private ImageView imgResult39;
    private TextView tvQuestion40;
    private ImageView imgResult40;
    private TextView tvQuestion41;
    private ImageView imgResult41;
    private TextView tvQuestion42;
    private ImageView imgResult42;
    private TextView tvQuestion43;
    private ImageView imgResult43;
    private TextView tvQuestion44;
    private ImageView imgResult44;
    private TextView tvQuestion45;
    private ImageView imgResult45;
    private TextView tvQuestion46;
    private ImageView imgResult46;
    private TextView tvQuestion47;
    private ImageView imgResult47;
    private TextView tvQuestion48;
    private ImageView imgResult48;
    private TextView tvQuestion49;
    private ImageView imgResult49;
    private TextView tvQuestion50;
    private ImageView imgResult50;




    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list_question_did);
        init();


    }
    private void init(){

        tvQuestion1 = (TextView) findViewById(R.id.tvQuestion1);
        imgResult1 = (ImageView) findViewById(R.id.imgResult1);
        tvQuestion2 = (TextView) findViewById(R.id.tvQuestion2);
        imgResult2 = (ImageView) findViewById(R.id.imgResult2);
        tvQuestion3 = (TextView) findViewById(R.id.tvQuestion3);
        imgResult3 = (ImageView) findViewById(R.id.imgResult3);
        tvQuestion4 = (TextView) findViewById(R.id.tvQuestion4);
        imgResult4 = (ImageView) findViewById(R.id.imgResult4);
        tvQuestion5 = (TextView) findViewById(R.id.tvQuestion5);
        imgResult5 = (ImageView) findViewById(R.id.imgResult5);
        tvQuestion6 = (TextView) findViewById(R.id.tvQuestion6);
        imgResult6 = (ImageView) findViewById(R.id.imgResult6);
        tvQuestion7 = (TextView) findViewById(R.id.tvQuestion7);
        imgResult7 = (ImageView) findViewById(R.id.imgResult7);
        tvQuestion8 = (TextView) findViewById(R.id.tvQuestion8);
        imgResult8 = (ImageView) findViewById(R.id.imgResult8);
        tvQuestion9 = (TextView) findViewById(R.id.tvQuestion9);
        imgResult9 = (ImageView) findViewById(R.id.imgResult9);
        tvQuestion10 = (TextView) findViewById(R.id.tvQuestion10);
        imgResult10 = (ImageView) findViewById(R.id.imgResult10);
        tvQuestion11 = (TextView) findViewById(R.id.tvQuestion11);
        imgResult11 = (ImageView) findViewById(R.id.imgResult11);
        tvQuestion12 = (TextView) findViewById(R.id.tvQuestion12);
        imgResult12 = (ImageView) findViewById(R.id.imgResult12);
        tvQuestion13 = (TextView) findViewById(R.id.tvQuestion13);
        imgResult13 = (ImageView) findViewById(R.id.imgResult13);
        tvQuestion14 = (TextView) findViewById(R.id.tvQuestion14);
        imgResult14 = (ImageView) findViewById(R.id.imgResult14);
        tvQuestion15 = (TextView) findViewById(R.id.tvQuestion15);
        imgResult15 = (ImageView) findViewById(R.id.imgResult15);
        tvQuestion16 = (TextView) findViewById(R.id.tvQuestion16);
        imgResult16 = (ImageView) findViewById(R.id.imgResult16);
        tvQuestion17 = (TextView) findViewById(R.id.tvQuestion17);
        imgResult17 = (ImageView) findViewById(R.id.imgResult17);
        tvQuestion18 = (TextView) findViewById(R.id.tvQuestion18);
        imgResult18 = (ImageView) findViewById(R.id.imgResult18);
        tvQuestion19 = (TextView) findViewById(R.id.tvQuestion19);
        imgResult19 = (ImageView) findViewById(R.id.imgResult19);
        tvQuestion20 = (TextView) findViewById(R.id.tvQuestion20);
        imgResult20 = (ImageView) findViewById(R.id.imgResult20);
        tvQuestion21 = (TextView) findViewById(R.id.tvQuestion21);
        imgResult21 = (ImageView) findViewById(R.id.imgResult21);
        tvQuestion22 = (TextView) findViewById(R.id.tvQuestion22);
        imgResult22 = (ImageView) findViewById(R.id.imgResult22);
        tvQuestion23 = (TextView) findViewById(R.id.tvQuestion23);
        imgResult23 = (ImageView) findViewById(R.id.imgResult23);
        tvQuestion24 = (TextView) findViewById(R.id.tvQuestion24);
        imgResult24 = (ImageView) findViewById(R.id.imgResult24);
        tvQuestion25 = (TextView) findViewById(R.id.tvQuestion25);
        imgResult25 = (ImageView) findViewById(R.id.imgResult25);
        tvQuestion26 = (TextView) findViewById(R.id.tvQuestion26);
        imgResult26 = (ImageView) findViewById(R.id.imgResult26);
        tvQuestion27 = (TextView) findViewById(R.id.tvQuestion27);
        imgResult27 = (ImageView) findViewById(R.id.imgResult27);
        tvQuestion28 = (TextView) findViewById(R.id.tvQuestion28);
        imgResult28 = (ImageView) findViewById(R.id.imgResult28);
        tvQuestion29 = (TextView) findViewById(R.id.tvQuestion29);
        imgResult29 = (ImageView) findViewById(R.id.imgResult29);
        tvQuestion30 = (TextView) findViewById(R.id.tvQuestion30);
        imgResult30 = (ImageView) findViewById(R.id.imgResult30);
        tvQuestion31 = (TextView) findViewById(R.id.tvQuestion31);
        imgResult31 = (ImageView) findViewById(R.id.imgResult31);
        tvQuestion32 = (TextView) findViewById(R.id.tvQuestion32);
        imgResult32 = (ImageView) findViewById(R.id.imgResult32);
        tvQuestion33 = (TextView) findViewById(R.id.tvQuestion33);
        imgResult33 = (ImageView) findViewById(R.id.imgResult33);
        tvQuestion34 = (TextView) findViewById(R.id.tvQuestion34);
        imgResult34 = (ImageView) findViewById(R.id.imgResult34);
        tvQuestion35 = (TextView) findViewById(R.id.tvQuestion35);
        imgResult35 = (ImageView) findViewById(R.id.imgResult35);
        tvQuestion36 = (TextView) findViewById(R.id.tvQuestion36);
        imgResult36 = (ImageView) findViewById(R.id.imgResult36);
        tvQuestion37 = (TextView) findViewById(R.id.tvQuestion37);
        imgResult37 = (ImageView) findViewById(R.id.imgResult37);
        tvQuestion38 = (TextView) findViewById(R.id.tvQuestion38);
        imgResult38 = (ImageView) findViewById(R.id.imgResult38);
        tvQuestion39 = (TextView) findViewById(R.id.tvQuestion39);
        imgResult39 = (ImageView) findViewById(R.id.imgResult39);
        tvQuestion40 = (TextView) findViewById(R.id.tvQuestion40);
        imgResult40 = (ImageView) findViewById(R.id.imgResult40);
        tvQuestion41 = (TextView) findViewById(R.id.tvQuestion41);
        imgResult41 = (ImageView) findViewById(R.id.imgResult41);
        tvQuestion42 = (TextView) findViewById(R.id.tvQuestion42);
        imgResult42 = (ImageView) findViewById(R.id.imgResult42);
        tvQuestion43 = (TextView) findViewById(R.id.tvQuestion43);
        imgResult43 = (ImageView) findViewById(R.id.imgResult43);
        tvQuestion44 = (TextView) findViewById(R.id.tvQuestion44);
        imgResult44 = (ImageView) findViewById(R.id.imgResult44);
        tvQuestion45 = (TextView) findViewById(R.id.tvQuestion45);
        imgResult45 = (ImageView) findViewById(R.id.imgResult45);
        tvQuestion46 = (TextView) findViewById(R.id.tvQuestion46);
        imgResult46 = (ImageView) findViewById(R.id.imgResult46);
        tvQuestion47 = (TextView) findViewById(R.id.tvQuestion47);
        imgResult47 = (ImageView) findViewById(R.id.imgResult47);
        tvQuestion48 = (TextView) findViewById(R.id.tvQuestion48);
        imgResult48 = (ImageView) findViewById(R.id.imgResult48);
        tvQuestion49 = (TextView) findViewById(R.id.tvQuestion49);
        imgResult49 = (ImageView) findViewById(R.id.imgResult49);
        tvQuestion50 = (TextView) findViewById(R.id.tvQuestion50);
        imgResult50 = (ImageView) findViewById(R.id.imgResult50);

    }
}
